//package persistence.jpa
//
//import interceptors.QueryPulseInterceptor
//import model.QueryError
//import model.QueryEvent
//import util.PulseContextHolder
//import java.io.PrintWriter
//import java.sql.*
//import java.util.logging.Logger
//import javax.sql.DataSource
//
///**
// * A [DataSource] proxy that wraps every [Connection] to intercept all JDBC
// * statements. Drop this in place of your real DataSource — Spring Boot
// * auto-configuration does this automatically via [PulseDataSourceBeanPostProcessor].
// *
// * Intercepts:
// *  - Statement.execute / executeQuery / executeUpdate
// *  - PreparedStatement (with parameter capture)
// *  - executeBatch()
// *
// * Hands results to all registered [QueryPulseInterceptor] instances.
// */
//class PulseDataSourceProxy(
//    private val delegate: DataSource,
//    private val interceptors: List<QueryPulseInterceptor>,
////    private val config: PulseQueryConfig
//) : DataSource by delegate {
//
//    override fun getConnection(): Connection =
//        PulseConnectionProxy(delegate.connection, interceptors, config)
//
//    override fun getConnection(username: String, password: String): Connection =
//        PulseConnectionProxy(delegate.getConnection(username, password), interceptors, config)
//
//    // Delegate everything else via the `by delegate` above
//    override fun getLogWriter(): PrintWriter = delegate.logWriter
//    override fun setLogWriter(out: PrintWriter) { delegate.logWriter = out }
//    override fun setLoginTimeout(seconds: Int) { delegate.loginTimeout = seconds }
//    override fun getLoginTimeout(): Int = delegate.loginTimeout
//    override fun getParentLogger(): Logger = delegate.parentLogger
//    override fun <T : Any> unwrap(iface: Class<T>): T = delegate.unwrap(iface)
//    override fun isWrapperFor(iface: Class<*>): Boolean = delegate.isWrapperFor(iface)
//}
//
//// ---------------------------------------------------------------------------
//// Connection proxy
//// ---------------------------------------------------------------------------
//
//internal class PulseConnectionProxy(
//    private val delegate: Connection,
//    private val interceptors: List<QueryPulseInterceptor>,
//    private val config: PulseQueryConfig
//) : Connection by delegate {
//
//    override fun createStatement(): Statement =
//        PulseStatementProxy(delegate.createStatement(), interceptors, config, null)
//
//    override fun prepareStatement(sql: String): PreparedStatement =
//        PulsePreparedStatementProxy(delegate.prepareStatement(sql), sql, interceptors, config)
//
//    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
//        PulsePreparedStatementProxy(
//            delegate.prepareStatement(sql, autoGeneratedKeys), sql, interceptors, config
//        )
//
//    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
//        PulsePreparedStatementProxy(
//            delegate.prepareStatement(sql, columnIndexes), sql, interceptors, config
//        )
//
//    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
//        PulsePreparedStatementProxy(
//            delegate.prepareStatement(sql, columnNames), sql, interceptors, config
//        )
//
//    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement =
//        PulsePreparedStatementProxy(
//            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), sql, interceptors, config
//        )
//
//    override fun prepareStatement(
//        sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int
//    ): PreparedStatement =
//        PulsePreparedStatementProxy(
//            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability),
//            sql, interceptors, config
//        )
//}
//
//// ---------------------------------------------------------------------------
//// Statement proxy (plain Statement — no parameters)
//// ---------------------------------------------------------------------------
//
//internal class PulseStatementProxy(
//    private val delegate: Statement,
//    private val interceptors: List<QueryPulseInterceptor>,
////    private val config: PulseQueryConfig,
//    private val fixedSql: String?      // non-null for PreparedStatement subclass usage
//) : Statement by delegate {
//
//    private val batchSqls = mutableListOf<String>()
//
//    override fun execute(sql: String): Boolean = intercept(sql) { delegate.execute(sql) } as Boolean
//    override fun executeQuery(sql: String): ResultSet = intercept(sql) { delegate.executeQuery(sql) } as ResultSet
//    override fun executeUpdate(sql: String): Int = intercept(sql) { delegate.executeUpdate(sql) } as Int
//
//    override fun addBatch(sql: String) {
//        batchSqls.add(sql)
//        delegate.addBatch(sql)
//    }
//
//
//    override fun executeBatch(): IntArray {
//        val started = System.currentTimeMillis()
//        val result = runCatching { delegate.executeBatch() }
//        val duration = System.currentTimeMillis() - started
//        val ctx = PulseContextHolder.get()
//
//        val events = batchSqls.mapIndexed { i, sql ->
//            buildEvent(
//                sql = sql,
//                started = started,
//                durationMs = duration,            // approximate — whole batch duration
//                rowsAffected = result.getOrNull()?.getOrElse(i) { 0 } ?: 0,
//                error = result.exceptionOrNull()?.toQueryError()
//            )
//        }
//
//        if (ctx != null) {
//            interceptors.forEach { it.onBatch(ctx, events) }
//        }
//
//        batchSqls.clear()
//        result.getOrThrow()   // re-throw if the batch failed
//        return result.getOrThrow()
//    }
//
//    protected fun <T> intercept(sql: String, block: () -> T): T {
//        val started = System.currentTimeMillis()
//        val result = runCatching { block() }
//        val duration = System.currentTimeMillis() - started
//
//        val rowsAffected = when (val v = result.getOrNull()) {
//            is Int -> v
//            else   -> 0
//        }
//
//        val event = buildEvent(
//            sql = sql,
//            started = started,
//            durationMs = duration,
//            rowsAffected = rowsAffected,
//            error = result.exceptionOrNull()?.toQueryError()
//        )
//
//        val ctx = PulseContextHolder.get()
//        if (ctx != null) {
//            notifyInterceptors(ctx, event)
//        }
//
//        return result.getOrThrow()
//    }
//
//    private fun buildEvent(
//        sql: String,
//        started: Long,
//        durationMs: Long,
//        rowsAffected: Int,
//        error: QueryError?
//    ): QueryEvent {
//        val normalized = SqlNormalizer.normalize(sql)
//        val isSlowQuery = durationMs >= config.slowQueryThresholdMs
//
//        // N+1 detection
//        val ctx = PulseContextHolder.get()
//        val occurrences = ctx?.let {
//            PulseContextHolder.recordQueryPattern(normalized, SqlNormalizer.extractTableName(sql))
//        } ?: 1
//        val isNPlusOne = occurrences > config.nPlusOneThreshold
//
//        return QueryEvent(
//            sql = sql,
//            queryType = SqlNormalizer.inferQueryType(sql),
//            tableName = SqlNormalizer.extractTableName(sql),
//            startedAt = started,
//            durationMs = durationMs,
//            rowsAffected = rowsAffected,
//            isSlowQuery = isSlowQuery,
//            isPotentialNPlusOne = isNPlusOne,
//            error = error,
//            dataSource = config.dataSourceName
//        )
//    }
//
//    private fun notifyInterceptors(ctx: model.PulseContext, event: QueryEvent) {
//        interceptors.forEach { it.onQuery(ctx, event) }
//        if (event.isSlowQuery) interceptors.forEach { it.onSlowQuery(ctx, event) }
//        if (event.isPotentialNPlusOne) {
//            interceptors.forEach {
//                it.onNPlusOneDetected(ctx, SqlNormalizer.normalize(event.sql),
//                    PulseContextHolder.recordQueryPattern(SqlNormalizer.normalize(event.sql), event.tableName))
//            }
//        }
//    }
//}
//
//// ---------------------------------------------------------------------------
//// PreparedStatement proxy (captures bound parameters)
//// ---------------------------------------------------------------------------
//
//internal class PulsePreparedStatementProxy(
//    private val delegate: PreparedStatement,
//    private val sql: String,
//    interceptors: List<QueryPulseInterceptor>,
//    config: PulseQueryConfig
//) : PulseStatementProxy(delegate, interceptors, config, sql), PreparedStatement by delegate {
//
//    // Parameter capture — index → string representation
//    private val params = mutableMapOf<Int, String?>()
//
//    override fun execute(): Boolean          = intercept(sql) { delegate.execute() } as Boolean
//    override fun executeQuery(): ResultSet   = intercept(sql) { delegate.executeQuery() } as ResultSet
//    override fun executeUpdate(): Int        = intercept(sql) { delegate.executeUpdate() } as Int
//
//    // Capture each setXxx call
//    override fun setNull(parameterIndex: Int, sqlType: Int) {
//        params[parameterIndex] = null; delegate.setNull(parameterIndex, sqlType)
//    }
//    override fun setBoolean(parameterIndex: Int, x: Boolean) {
//        params[parameterIndex] = x.toString(); delegate.setBoolean(parameterIndex, x)
//    }
//    override fun setInt(parameterIndex: Int, x: Int) {
//        params[parameterIndex] = x.toString(); delegate.setInt(parameterIndex, x)
//    }
//    override fun setLong(parameterIndex: Int, x: Long) {
//        params[parameterIndex] = x.toString(); delegate.setLong(parameterIndex, x)
//    }
//    override fun setDouble(parameterIndex: Int, x: Double) {
//        params[parameterIndex] = x.toString(); delegate.setDouble(parameterIndex, x)
//    }
//    override fun setString(parameterIndex: Int, x: String?) {
//        params[parameterIndex] = x; delegate.setString(parameterIndex, x)
//    }
//    override fun setObject(parameterIndex: Int, x: Any?) {
//        params[parameterIndex] = x?.toString(); delegate.setObject(parameterIndex, x)
//    }
//    override fun setTimestamp(parameterIndex: Int, x: java.sql.Timestamp?) {
//        params[parameterIndex] = x?.toString(); delegate.setTimestamp(parameterIndex, x)
//    }
//    override fun setDate(parameterIndex: Int, x: java.sql.Date?) {
//        params[parameterIndex] = x?.toString(); delegate.setDate(parameterIndex, x)
//    }
//    override fun setBigDecimal(parameterIndex: Int, x: java.math.BigDecimal?) {
//        params[parameterIndex] = x?.toString(); delegate.setBigDecimal(parameterIndex, x)
//    }
//
//    override fun clearParameters() {
//        params.clear(); delegate.clearParameters()
//    }
//
//    fun capturedParameters(): List<String?> =
//        (1..params.size).map { params[it] }
//}
//
//// ---------------------------------------------------------------------------
//// Helpers
//// ---------------------------------------------------------------------------
//
//private fun Throwable.toQueryError() = QueryError(
//    sqlState = (this as? SQLException)?.sqlState,
//    errorCode = (this as? SQLException)?.errorCode ?: -1,
//    message = message ?: "Unknown error",
//    exceptionClass = this::class.java.name
//)