package com.kraftadmin.enums

enum class FormInputType {
    TEXT, TEXTAREA, NUMBER, EMAIL, PASSWORD, DATE,
    DATETIME, SELECT, MULTI_RELATION, CHECKBOX, IMAGE, ARRAY,
    VIDEO, FILE, JSON, COLOR, UNSET, OBJECT, RANGE, TIME, TEL, RADIO, WYSIWYG, URL, RELATION
}
